### ISSUE TITLE
Missing clicks when using m5encoder

### ISSUE THREAD

**Issue by tialm** [fstengel/m5LvglFiles#2]
Hi @fstengel ! Great work you have been doing here! Think it will be very useful.
So I was giving a try to your m5encoder library but I am getting missed clicks.
For what I have tried the OK button seems to work fine ( need to give it some more proper testing). But the left and right buttons don't recognize the presses half the time. Any suggestion on how to fine tune it? 
Thank you!

**Comment by tialm** [comment]
I tried to change the step. If step = 2 or 3 sometimes if I press left or right it won't move. If I set it to 1 it will double or triple click sometimes.

**Comment by fstengel** [comment]
This is the main problem. Every time the encoder is read it updates its internals: the (internal) diff and pressed properties. The thing is if I update the diff every update then one has multiple clicks, if one waits 2, 3 and more cycles then one has to press the button a bit longer and risks missed presses.

So: with a larger step one has to press A or C longer (not click, but press) in order for that press to register. See how long you have to press if you use `step=5`in order to get a reaction
